name: mamba-attn
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - cudatoolkit=11.8
  - pip:
      - torch==2.1.1
      - torchvision 
      - packaging
      - tb-nightly
      - gradio==3.33.1
      - albumentations==1.3.0
      - opencv-contrib-python
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.5.0
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - einops==0.6.0
      - transformers==4.36.2
      - webdataset==0.2.5
      - kornia==0.6
      - open_clip_torch==2.16.0
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==0.6.0
      - timm==0.6.12
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors==0.3.1
      - basicsr==1.4.2
      - accelerate==0.17.0
      - decord==0.6.0
      - diffusers==0.25
      - moviepy==1.0.3
      - opencv_python==4.7.0.68
      - Pillow==9.4.0
      - scikit_image==0.19.3
      - scipy==1.10.1
      - tensorboardX==2.6
      - tqdm==4.64.1
      - numpy 
      - datasets
      - ipython
      - seaborn
      - pycocotools
      - ipdb
      - matplotlib
      - flow_vis
      - charset-normalizer
      - ml_collections
      - wandb
      - causal-conv1d==1.2.0.post2
      - galore-torch